//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CompanySite.Models
{
    public partial class LoginLog
    {
        public int LoginLogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
    
        public virtual User User { get; set; }
    }
    
}
