//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CompanySite.Models
{
    public partial class Partner
    {
        public int PartnerId { get; set; }
        public Nullable<int> Hits { get; set; }
        public string Content { get; set; }
        public bool IsTop { get; set; }
        public bool IsElite { get; set; }
        public bool IsUrl { get; set; }
        public bool IsShow { get; set; }
        public bool IsImage { get; set; }
        public string LinkUrl { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public int UserId { get; set; }
    }
    
}
