//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CompanySite.Models
{
    public partial class ProjectClass
    {
        public ProjectClass()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public string Summary { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
    
}
